# Generated by Django 6.0 on 2026-03-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2m_app', '0002_alter_product_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
