# Generated by Django 6.0.3 on 2026-04-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    try:
        BuyerProfile = apps.get_model('f2m_app', 'BuyerProfile')
        FarmerProfile = apps.get_model('f2m_app', 'FarmerProfile')
        Profile = apps.get_model('f2m_app', 'Profile')
        Cart = apps.get_model('f2m_app', 'Cart')
        Product = apps.get_model('f2m_app', 'Product')
    except LookupError:
        # If models don't exist in history, skip
        return

    # Migrate Buyers
    for bp in BuyerProfile.objects.all():
        p = Profile.objects.create(
            user=bp.user,
            role='buyer',
            delivery_address=bp.delivery_address
        )
        # Update Cart (at this point in migration, buyer field is temporarily an integer)
        Cart.objects.filter(buyer=bp.buyer_id).update(buyer=p.profile_id)

    # Migrate Farmers
    for fp in FarmerProfile.objects.all():
        p = Profile.objects.create(
            user=fp.user,
            role='farmer',
            farm_name=fp.farm_name,
            farm_location=fp.farm_location,
            bio=fp.bio
        )
        # Update Products (at this point in migration, farmer field is temporarily an integer)
        Product.objects.filter(farmer=fp.farmer_id).update(farmer=p.profile_id)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('f2m_app', '0004_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create the new Profile model
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default='buyer', max_length=20)),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_location', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # 2. Convert FK fields to temporary integers to drop constraints
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.IntegerField(null=True),
        ),
        # 3. Run the data migration
        migrations.RunPython(migrate_data),
        # 4. Re-establish foreign keys pointing to the new Profile model
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='f2m_app.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='f2m_app.profile'),
        ),
        # 5. Clean up old fields and models
        migrations.RemoveField(
            model_name='farmerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
